### ISSUE TITLE
Setup infrastructure for RTL layouts

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cc-vocabulary#15]
Currently Vocabulary has been designed only with left-to-right layouts in mind. While this is acceptable for most languages, a number of languages, notably Arabic, are written right-to-left (RTL).

Support for RTL layouts is a crucial part of internationalisation and cannot be overlooked. The goal is to incorporate support for RTL layouts into the framework integrated with Vue-i18n so as to automatically switch to RTL whenever the active locale calls for it.

**Comment by HAMZABoxer98** [comment]
Arabic, Hebrew and Persian are RTL languages, I have a good knowledge about RTL essentials.. so I would work on this.
but I think we should make a discussion first.

**Comment by dhruvkb** [comment]
@HAMZABoxer98 you surely are suited for this task! Feel free to initiate a discussion on the technology we would need to implement this.

**Comment by dhruvkb** [comment]
Have you taken a look at the [`dir` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir)? It is a global attribute that was specifically designed to handle RTL layouts.

**Comment by dhruvkb** [comment]
So the idea would be to maintain a list of known RTL languages (or even better, define the directionality of the locale in a `direction` key from the Locale component's [localeList](https://github.com/creativecommons/cc-vocabulary/blob/64148c8948ff84f7d7eed4654a838280f5db4e4e/src/patterns/Locale/Locale.vue#L48)) and if the locale has RTL-directionality, set the `dir` attribute on the HTML tag itself by accessing `document.documentElement` when locale is changed.

You'll have to wait for #31 to be merged before working on this though.

**Comment by HAMZABoxer98** [comment]
@dhruvkb , some Elements ( Components ) may need additional styling and `dir="rtl"` won't work with it.
example: button with `call-to-action` attribute has a `clip-path` styling to the right, so I need to change it to the left for RTL.

**Comment by dhruvkb** [comment]
This issue pertains to setting up the core infrastructure for RTL. We'll deal with component-specific RTL changes in separate issues.

**Comment by HAMZABoxer98** [comment]
okay, once #31 is merged I will work on this.
