### ISSUE TITLE
Make Vocabulary robot-friendly

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cc-vocabulary#26]
Vocabulary currently has no meta tags for SEO and for rich-snippets in social media posts. The goal is to add meta tags for the homepage, storybook and styleguide. This has some negative impact as it makes sharing the URL to the project unappealing.

**Comment by dhruvkb** [comment]
This has been implemented, to some extent, by commit 19f0f91. This means that the root documentation site has meta information. Work remains on adding this information to the storybook and the styleguide.

**Comment by dhruvkb** [comment]
PR #35 adds meta tags to the storybook. Only the styleguide remains to be made SEO optimised.

**Comment by hdrdla** [comment]
Hi, I am an Outreachy applicant. May I be assigned this issue?

**Comment by dhruvkb** [comment]
Resolved in 352f794.
