### ISSUE TITLE
Write locale to and read locale from browser storage

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cc-vocabulary#27]
Currently locale change is restricted to current page. As soon as page reloads, locale reverts to the default, which is 'en'.

**Describe the steps to reproduce the bug**
1. Open an page powered by Vocabulary.
1. Change locale.
1. Navigate to a different page.

The locale is supposed to remain the chosen one. But it reverts to the default one. This is because the locale is never given any form of permanence. The goal is to write the chosen locale to the local storage and read from there on every reload. This will allow the locale change to persist across sessions and reloads.

**Comment by mansivx** [comment]
Hi! Can I work on this?
I know javascript but just started learning vue.
This seems doable, not too complex or framework specific.

**Comment by dhruvkb** [comment]
Sure, go ahead! Make sure that the code is integrated into the library and _not_ dependent on the parent application.

**Comment by dhruvkb** [comment]
@Pilgrim001, it seems this issue is not being worked on. Your PR will be ready to go once https://github.com/creativecommons/cc-vocabulary/pull/31#issuecomment-536979930 is addressed.

**Comment by HAMZABoxer98** [comment]
why this issue is still open ? seems that it is solved !.

**Comment by dhruvkb** [comment]
@HAMZABoxer98 as of right now, this has not been solved. A PR #31 is open to resolve this and will automatically close this when merged.

**Comment by dhruvkb** [comment]
Resolved in a884c94.
