### ISSUE TITLE
Use margins for better alignment in the Header component

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cc-vocabulary#28]
Currently the `Header` component uses a weird combination of flex grow and shrink to position elements in a split layout. However MDN suggests a cleaner way under the section 'Alignment and auto margins' in [this article](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Alignment/Box_Alignment_in_Flexbox).

Using this approach will greatly increase the code quality and remove a lot of assumptions, quirks and hacks under the hood.

**Comment by bax-uva** [comment]
Hello, I'm an Outreachy applicant. Can I work on this issue?

**Comment by dhruvkb** [comment]
Yeah sure, go ahead!

**Comment by MysticNas** [comment]
hey, im an outreachy applicant id like to make my first contribution.

Can I work on it as well?

**Comment by dhruvkb** [comment]
Sorry @MysticNas, this issue is already being worked on by @bax-uva. There are a number of other issues that you can work on.
