### ISSUE TITLE
Use service to serve documentation

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cc-vocabulary#37]
Instead of having a `docs/` directory in the codebase that must be manually updated by running 
```
npm run build:documentation
```
we should use a service such as [Zeit](https://zeit.co/) or [Netlify](https://www.netlify.com/) to continuously build and serve the docs whenever new commits are pushed to the branch `master`.

**Comment by HAMZABoxer98** [comment]
@dhruvkb , check this:
https://5d98717840eaac430b8bc2e2--hungry-lamport-e429e3.netlify.com/
I deployed the styleguide, do you want to link it with custom domain ?

**Comment by dhruvkb** [comment]
@HAMZABoxer98 great work! One question I must ask is why Netlify over Zeit? Are there any specific limitations of Zeit that Netlify resolves (asking because I personally am a bigger fan of Zeit)?

**Comment by dhruvkb** [comment]
Also, would it be possible to deploy the complete Vocabulary website instead of just the styleguide? What I mean is can we deploy this exact tree (as seen [here](https://creativecommons.github.io/cc-vocabulary/))?

```
landing site
├── styleguide 
└── storybook
```

**Comment by dhruvkb** [comment]
Once we have a working deployment, we'll replace the `docs/` folder with a redirect.

**Comment by HAMZABoxer98** [comment]
> why Netlify over Zeit?

just because I had some experience with Netlify, but it serves static websites only. I didn't use Zeit before, but I can do it.
> would it be possible to deploy the complete Vocabulary website instead of just the styleguide?

yes, it's possible to serve the `/docs` folder, but I don't know why `index.html` doesn't work with me, both locally and Netlify, 

> Once we have a working deployment, we'll replace the docs/ folder with a redirect.

can you explain more please.

**Comment by dhruvkb** [comment]
To drive work on this forward #39 has been created.

**Comment by HAMZABoxer98** [comment]
I am working on adding Popup/ Tooltip component, once I finish I will take it.

**Comment by dhruvkb** [comment]
Vocabulary has now been [deployed](https://cc-vocabulary.netlify.com/) to Netlify as a continuous deployment provider, building straight from `refs/master`. Also all PRs will get a staging URL on Netlify :tada:.
