### ISSUE TITLE
ProgressBar broken on Chrome

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cc-vocabulary#61]
**Description**
All styling applied to the `ProgressBar` component vanishes in Google Chrome. 

**Expected behavior**
The styling that appears very nicely in Mozilla Firefox should also work in Google Chrome.

**Screenshots**
![image](https://user-images.githubusercontent.com/16580576/67614229-c6b01000-f7d6-11e9-8fbb-120d09e1f745.png)
^ Progress bars in Google Chrome

![image](https://user-images.githubusercontent.com/16580576/67614233-e47d7500-f7d6-11e9-9410-f8009dccc80d.png)
^ Progress bars in Mozilla Firefox

**Conditions:**
 - OS: Linux
 - Browser: Google Chrome
 - Version: 78

**Comment by chidexebere** [comment]
Hello @dhruvkb Can I work on this?

**Comment by dhruvkb** [comment]
Yes @chidexebere, please go on.
